apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supply-chain-risk

resources:
  - namespace.yaml
  - secrets.yaml
  - ../configs/flink-conf-configmap.yaml
  - ../configs/app-config-configmap.yaml
  - kafka.yaml
  - redis.yaml
  - postgres.yaml
  - gateway.yaml
  - enrichment.yaml
  - flink.yaml
  - prometheus.yaml
  - grafana.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: supply-chain-risk

images:
  - name: supply-chain-gateway
    newTag: latest
  - name: supply-chain-enrichment
    newTag: latest
  - name: supply-chain-flink-processor
    newTag: latest
